[Mail]
   sender = amhv@orange.fr
   cc = syl8022@orange.fr

# Prix divers
[Divers.PRIX]
   # Prix de la cotisation Famille
   cotisationFamille = 30
   # prix de la reduction Famille a partir du 2eme adherent si prix audelà de minReduc
   reducFamille = 15
   # Prix minimum pour obtenir la reduc famille
   minReduc = 900 
   # Prix pour une personne exterieur aux communes
   prixExterieur = 80  

[Locations.PRIX]
   autre = 150
   guitare = 60
   hautbois = 180


# Permet d'associer la clef au texte du formulaire
#  Le contenu de la clef doit se retrouver dans le texte du formulaire
#  La clef doit ensuite etre utilisé dans les autres sections
[Decouverte.Index]
   Eveil = EVEIL A LA MUSIQUE
   JardinMusical = JARDIN MUSICAL
   Orchestre = JE DECOUVRE LES INSTRUMENTS
   Instrument = 1ère ANNEE DE PRATIQUE INSTRUMENTALE
   Instrument2 = 2ème ANNEE DE PRATIQUE INSTRUMENTALE

# Champs qui sera affiché dans le pdf
[Decouverte.Texte]
   Eveil = EVEIL A LA MUSIQUE, sur 2 ans, 30mn pour MS, 45 mn pour GS; 180€/an
   JardinMusical = JARDIN MUSICAL, pour PS, 30mn / alternance parents/enseignant; 100€
   Orchestre = JE DECOUVRE LES INSTRUMENTS DE L'ORCHESTRE, pour CP, 45mn; 180€
   Instrument = 1ère ANNEE DE PRATIQUE INSTRUMENTALE, obligatoire du CE1 au CM2, solfège appliqué à l'instrument inclus, 45mn à 3, 30mn à 2, location d'instrument 1/2 tarif; 350€
   Instrument2 = 2ème ANNEE DE PRATIQUE INSTRUMENTALE, optionnelle, solfège appliqué à l'instrument inclus, 45mn à 3, 30mn à 2, location d'instrument 1/2 tarif; 350€. Notes: Si l'élève à déjà suivi la 1ere année de pratique instumentale, il peut à la place choisir le parcours complet. Avec accord de l'enseignant.

# Prix reduit obligatoire car mons de 21a
[Decouverte.PRIX.Reduit]
   Eveil = 180
   JardinMusical = 100
   Orchestre = 180
   Instrument = 350
   Instrument2 = 350
   # Indique la reduction de la location d instrument
   location = 0.5

# Permet d'associer la clef au texte du formulaire
#  Le contenu de la clef doit se retrouver dans le texte du formulaire
#  La clef doit ensuite etre utilisé dans les autres sections
[Parcours.Index]
   Collectif = COURS COLLECTIF
   Individuel25mn = COURS INDIVIDUEL 25mn
   Individuel30mn =  COURS INDIVIDUEL 30mn
   
# Champs qui sera affiché dans le pdf
[Parcours.Texte]
   Collectif = COURS COLLECTIF, 45mn à 3 ou 30mn à 2
   Individuel25mn = COURS INDIVIDUEL 25mn
   Individuel30mn =  COURS INDIVIDUEL 30mn
   

[Parcours.PRIX.Reduit]
   Collectif = 420
   Individuel25mn = 520
   Individuel30mn =  610

[Parcours.PRIX]
   Collectif = 470
   Individuel25mn =  570
   Individuel30mn =  660

# Permet d'associer la clef au texte du formulaire
#  Le contenu de la clef doit se retrouver dans le texte du formulaire
#  La clef doit ensuite etre utilisé dans les autres sections
[Amatteur.Index]
   Individuel25mn = COURS INDIVIDUEL 25mn
   Individuel30mn = COURS INDIVIDUEL 30mn
   Electronique =  MUSIQUE ELECTRONIQUE
   
# Champs qui sera affiché dans le pdf
[Amatteur.Texte]
   Individuel25mn = COURS INDIVIDUEL 25mn
   Individuel30mn = COURS INDIVIDUEL 30mn - tous les 15jours
   Electronique =  MUSIQUE ELECTRONIQUE - 1h tous les 15 jours pour 2 personnes
   
[Amatteur.PRIX.Reduit]
   Individuel25mn =  500
   Individuel30mn =  340
   Electronique = 340

[Amatteur.PRIX]
   Individuel25mn =  550
   Individuel30mn =  370
   Electronique = 370
   
# Permet d'associer la clef au texte du formulaire
#  Le contenu de la clef doit se retrouver dans le texte du formulaire
#  La clef doit ensuite etre utilisé dans les autres sections
[Orchestre.Index]
   Junior = ORCHESTRE JUNIOR CORDES ET VENTS
   ChoralEnfant = CHORALE ENFANTS A L
   Chorale = CHORALE ADULTE
   Orchestre = ORCHESTRE HARMONIE

   
# Champs qui sera affiché dans le pdf
[Orchestre.Texte]
   Junior = ORCHESTRE JUNIOR CORDES ET VENTS- 1h hebdo
   ChoralEnfant = CHORALE ENFANTS A L'ECOLE - 1h hebdo  - sous réserve d'approbation par les mairies
   Chorale = CHORALE ADULTE - 2h hebdo
   Orchestre = ORCHESTRE HARMONIE - 2h hebdo

[Orchestre.PRIX.Reduit]
   Junior=60
   ChoralEnfant=60
   Chorale=60
   Orchestre=60

[Orchestre.PRIX]
   Junior=80
   ChoralEnfant=60
   Chorale=130
   Orchestre=130

# Permet d'associer la clef au texte du formulaire
#  Le contenu de la clef doit se retrouver dans le texte du formulaire
#  La clef doit ensuite etre utilisé dans les autres sections
[Groupe.Index]
   Rock = GROUPE ROCK
   Jazz = ATELIER JAZZ
   Autonome = Accès à la pratique autonome
   
# Champs qui sera affiché dans le pdf
[Groupe.Texte]
   Rock = GROUPE ROCK - 1h hebdo
   Jazz = ATELIER JAZZ - 1h hebdo
   Autonome = Accès à la pratique autonome + prof 4h/année

[Groupe.PRIX.Reduit]
   Rock=180
   Jazz=180
   Autonome=50

[Groupe.PRIX]
   Rock=320
   Jazz=320
   Autonome=50

[Complement.Index]
   facture = J'ai besoin d'une facture
   sortir = Je bénificie du dispositif sortir
   volontaire = Je suis volontaire pour aider ponctuellement
   photo = J'autorise l'AMHV à utiliser des photos des élèves inscrits sur tout support de communication

[Complement.Texte]
   facture = J'ai besoin d'une facture
   sortir = Je bénificie du dispositif sortir (à activer en mairie)
   volontaire = Je suis volontaire pour aider ponctuellement lors d'événements (concert, audition, ...)
   photo = J'autorise l'AMHV à utiliser des photos des élèves inscrits sur tout support de communication

[Reglement.Index]
   integral = Règlement de l'intégralité
   3cheques = Règlement par chèque en 3 fois
   5prelevements =  prélèvement en 5 fois 
   1prelevement = Par prélèvement en 1 fois 
   vacance = Par chèques vacances 
                    
[Reglement.Texte]
   integral = Règlement de l'intégralité
   3cheques = Règlement par chèque en 3 fois
   5prelevements =  prélèvement en 5 fois (vers le 8 des mois d'octobre 2024, novembre 2024, décembre 2024, février 2025 et mars 2025) -  - le SEPA et le RIB sont alors nécessaire"
   1prelevement = Par prélèvement en 1 fois  - le SEPA et le RIB sont alors nécessaire
   vacance = Par chèques vacances - Un chèque de caution est nécessaire si vous êtes en attente de la réception de vos chèques.

[ReglementInterieur.Index]
   assurance = Je certifie être bien assuré
   reglemennt = Avoir pris connaissance du règlement intérieur
   presence = Je dois m'assurer de la présence de l'enseignant 
   fincours= Je dois m'assurer de la prise en charge
   refus = J'accepte de me voir refuser un cours collectif
   annulationt =  cours l'inscription est considérée comme définitive
   rgpd = Je suis informé·e que les informations recueillies


prixLoc = 150
prixLocGuit = 60
prixLocHaut = 180
CstPrixExterieur = 80  # Prix pour une personne exterieur aux communes
CstReducFamille = 15  # prix de la reduction Famille a partir du 2eme adherent au de à de minReduc
CstminReduc = 900  # Prix minimum pour obtenir la reduc famille
CstcotisationFamille = 30
